import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">V-core9</Link>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/register">
            <a className={styles.card}>
              <h2>Register Account &rarr;</h2>
              <p>Create your free account. No credit card required.</p>
            </a>
          </Link>

          <Link href="/terms-and-conditions" >
            <a className={styles.card}>
              <h2>Terms and Conditions &rarr;</h2>
              <p>Learn about our boilerplate example terms and conditions!</p>
            </a>
          </Link>

          <Link href="/login">
            <a className={styles.card}>
              <h2>Login &rarr;</h2>
              <p>Existing users can quickly login using this page.</p>
            </a>
          </Link>

          <Link href="/mui-demo" >
            <a className={styles.card}>
              <h2>MUI Demo &rarr;</h2>
              <p>
                Example of Material UI library for react in Next.
              </p>
            </a>
          </Link>

          <Link href="/forgot-password">
            <a className={styles.card}>
              <h2>Forgot Password &rarr;</h2>
              <p>
                This is a page where user can ask for password reset link.
              </p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <a>
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </Link>
      </footer>
    </div>
  )
}

export default Home
