import { GetServerSideProps } from "next"
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import PageLayout from '../components/PageLayout';
import pagesService from '../services/pages';


const { listPages } = pagesService;

export const getServerSideProps: GetServerSideProps = async (context: any) => {
  // console.log(context);

  const pages = JSON.parse(JSON.stringify(await listPages({})));

  const props: any = {
    pages,
  }

  console.log(props);

  return ((!pages || pages.length === 0) ? { props: {} } : {
    props,
  });
}


const SupportPage: NextPage<any> = (props: any = {}) => {

  const staticPages = [
    {
      url: '/',
      name: 'Home Page 🏠',
      desc: 'Websites Index Landing Page, so called Homepage.'
    },
    {
      url: '/register',
      name: 'Register Account 🚀',
      desc: 'Create your free account. No credit card required'
    },
    {
      url: '/application',
      name: 'Application Page ⚡',
      desc: 'Example of Material UI library for react in Next.'
    },
    {
      url: '/terms-and-conditions',
      name: 'Terms and Conditions 📃',
      desc: 'Learn about our boilerplate example terms and conditions!'
    },
    {
      url: '/login',
      name: 'Login Page 🔐',
      desc: 'Existing users can quickly login using this page.'
    },
    {
      url: '/forgot-password',
      name: 'Forgot Password 🔎',
      desc: 'This is a page where user can ask for password reset link.'
    },
    {
      url: '/support',
      name: 'Support 🆘',
      desc: 'Basically this page.'
    },
    {
      url: '/github-insides/',
      name: 'GitHub Insides 🦼',
      desc: 'Search User Github Stats.'
    },
  ]

  return (
    <PageLayout title="V-core9 - Support List of Pages" description="Generated by create next app" >
      <>
        <h1 className={styles.title}>
          List of available pages
        </h1>

        <main className={styles.main}>
          <h2>
            Static Pages
          </h2>

          <div className={styles.grid}>
            {
              staticPages.map((item) => {
                return (
                  // eslint-disable-next-line react/jsx-key
                  <Link href={item.url}>
                    <a className={styles.card}>
                      {item.name ? <h2>{item.name}</h2> : 'Missing Page Name'}
                      {item.desc && <p>{item.desc}</p>}
                    </a>
                  </Link>
                )
              })
            }
          </div>


          <h2>
            Dynamic Pages
          </h2>

          <div className={styles.grid}>
            {props.pages && props.pages.map((page: any) =>
              <Link key={page.id} href={page.slug}>
                <a className={styles.card}>
                  <h2>{page.title} 🏠</h2>
                  <p>Websites Index Landing Page, so called Homepage.</p>
                </a>
              </Link>
            )}
          </div>

        </main>
      </>
    </PageLayout>
  )
}

export default SupportPage
