import type { NextPage } from 'next';
import Avatar from '@mui/material/Avatar';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import LockOutlinedIcon from '@mui/icons-material/LockOutlined';
import Head from 'next/head';
import Link from 'next/link';

import Copyright from '../components/Copyright';
import DocHead from '../components/DocHead';

const theme = createTheme();

const TermsAndConditions: NextPage = () => {

  return (
    <ThemeProvider theme={theme}>

      <DocHead
        title="V-core9 - Terms and Conditions Page"
        description="Generated by create next app"
      />

      <Container component="main" maxWidth="sm"
        sx={{
          display: 'flex',
          flexDirection: 'column',
          gap: 1,
        }}>
        <CssBaseline />
        <Box
          sx={{
            marginTop: 8,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 1,
          }}
        >
          <Avatar sx={{ m: 1, bgcolor: 'secondary.main' }}>
            <LockOutlinedIcon />
          </Avatar>
          <Typography component="h1" variant="h4">
            Terms and Conditions
          </Typography>
        </Box>
        <Box
          sx={{
            marginTop: 2,
            display: 'flex',
            flexDirection: 'column',
            gap: 2
          }}
        >
          <Typography gutterBottom component="h2" variant="h5">
            Cras mattis consectetur purus sit amet fermentum.
          </Typography>
          <Typography gutterBottom component="p">
            Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
            Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
          </Typography>
          <Typography gutterBottom component="p">
            Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus
            magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec
            ullamcorper nulla non metus auctor fringilla.
          </Typography>
          <Typography gutterBottom component="h2" variant="h5">
            Cras mattis consectetur purus sit amet fermentum.
          </Typography>
          <Typography gutterBottom component="p">
            Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
            Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
          </Typography>
          <Typography gutterBottom component="p">
            Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus
            magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec
            ullamcorper nulla non metus auctor fringilla.
          </Typography>
          <Typography gutterBottom component="h2" variant="h5">
            Cras mattis consectetur purus sit amet fermentum.
          </Typography>
          <Typography gutterBottom component="p">
            Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
            Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
          </Typography>
          <Typography gutterBottom component="p">
            Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus
            magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec
            ullamcorper nulla non metus auctor fringilla.
          </Typography>
          <Typography gutterBottom component="h2" variant="h5">
            Cras mattis consectetur purus sit amet fermentum.
          </Typography>
          <Typography gutterBottom component="p">
            Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
            Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.
          </Typography>
          <Typography gutterBottom component="p">
            Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus
            magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec
            ullamcorper nulla non metus auctor fringilla.
          </Typography>
        </Box>
      </Container>
      <Copyright sx={{ mt: 5, padding: 1 }} />
    </ThemeProvider>
  );
}

export default TermsAndConditions;
